### ISSUE TITLE
docs: slightly incorrect setup instructions

### ISSUE THREAD

**Issue by sankalpmukim** [wagtail/docker-wagtail-develop#26]
![image](https://user-images.githubusercontent.com/41541375/114444193-33e27b80-9bec-11eb-8d42-518d2728cc3a.png)
![image](https://user-images.githubusercontent.com/41541375/114444217-37760280-9bec-11eb-8e15-6ff0944c90fb.png)
Slightly incorrect setup instructions. Because the git clone command given was not working, the cd command also needed to be changed. I think it is a simple documentation fix! I would be happy to be assigned this issue.

**Comment by Scotchester** [comment]
Hi @sankalpmukim! Thanks for opening this issue.

I think that we should probably not suggest cloning via the SSH protocol in our instructions. Folks will run into this permission denied issue if they have not added their public key to their GitHub account.

Let's change the command to use the default HTTPS protocol that GitHub now recommends:

`git clone https://github.com/wagtail/docker-wagtail-develop.git wagtail-dev`

Feel free to open a pull request with that change!
