### ISSUE TITLE
Problem with starting the container 

### ISSUE THREAD

**Issue by HelenaBahrami** [wagtail/docker-wagtail-develop#34]
Hi, 
Thank you for this rich and detailed repo.
I followed all the steps in the ReadME file but there was a problem with the start container step. I tried both command
`docker-compose up` and 
`CURRENT_UID=$(id -u):$(id -g) docker-compose -f docker-compose.yml -f docker-compose.linux.yml up`
the container started to build but it stopped after the webpack.progress completed %100 and didn't proceed further:

```
frontend    | runtime modules 135 KiB 273 modules
frontend    | modules by path ./node_modules/ 3.05 MiB 560 modules
frontend    | modules by path ./client/src/ 549 KiB
frontend    |   modules by path ./client/src/components/ 365 KiB 59 modules
frontend    |   modules by path ./client/src/entrypoints/ 166 KiB 35 modules
frontend    |   modules by path ./client/src/utils/ 5.33 KiB
frontend    |     modules by path ./client/src/utils/*.js 3.02 KiB 4 modules
frontend    |     modules by path ./client/src/utils/*.ts 2.31 KiB 2 modules
frontend    |   modules by path ./client/src/includes/*.js 3.8 KiB 3 modules
frontend    |   modules by path ./client/src/api/ 6.79 KiB
frontend    |     ./client/src/api/admin.ts 5.3 KiB [built] [code generated]
frontend    |     ./client/src/api/client.js 1.49 KiB [built] [code generated]
frontend    |   ./client/src/config/wagtailConfig.js 735 bytes [built] [code generated]
frontend    |   ./client/src/index.ts 1.6 KiB [built] [code generated]
frontend    | external "jQuery" 42 bytes [built] [code generated]
frontend    | webpack compiled successfully in 27108 ms
frontend    | <s> [webpack.Progress] 99% cache store build dependencies
frontend    | <s> [webpack.Progress] 99% cache store build dependencies
frontend    | <s> [webpack.Progress] 99% cache begin idle
frontend    | <s> [webpack.Progress] 99% cache begin idle
frontend    | <s> [webpack.Progress] 100% 
frontend    | 
```

can you please help me to understand the problem and solve it?

**Comment by vupham04** [comment]
Hi, which distribution did you run it on? And while docker-compose is up, did you try to access the webpage http://localhost:8000? It seems that this is not really an error - mine stops at 100% too, and you are supposed to leave it there, open a new terminal and do your work

**Comment by vupham04** [comment]
It seems that this issue should be closed because this is not really a bug. Hope someone can investigate it and close it soon!

**Comment by saevarom** [comment]
This is probably not an issue.
