### ISSUE TITLE
Run tests command does not work when using docker-compose exec.

### ISSUE THREAD

**Issue by thoang43** [wagtail/docker-wagtail-develop#35]
After following all the steps in the documentation for installing docker-wagtail-develop, we tried to run the `python runtests.py` through `docker-compose exec web python ../wagtail/runtests.py` . However, the result showed that there was 0 test run. The tests will only be run if we specify a specific part such as `docker-compose exec web python ../wagtail/runtests.py wagtail.core`. We tried to run on two different environments:
- WSL2 Ubuntu 20.04, Docker Desktop on Windows
- Ubuntu 20.04 on VirtualBox

However, if we install manually by installing all dependencies and run `python runtests.py` directly on the command line, more than 4000 tests will be run.

We believe this is a bug that is specifically on the docker-wagtail-develop and need to be fixed so that the runtests.py will run all tests.

**Comment by saevarom** [comment]
It looks like you now have to specify the working directory to run the tests. Readme updated but the command is:

`docker-compose exec -w /code/wagtail web python runtests.py`
