### ISSUE TITLE
Models in app(s): 'blog' have changes that are not yet reflected in a migration

### ISSUE THREAD

**Issue by vupham04** [wagtail/docker-wagtail-develop#42]
When I try to run ./setup-db.sh, an error appears like the image below. I wonder that this is an issue?

![image](https://user-images.githubusercontent.com/46913707/160225825-18c7d4ca-1427-46ab-bc89-922d5b172c0b.png)

**Comment by saevarom** [comment]
Hi @vupham04 
Are you doing this on a fresh install of `docker-wagtail-develop`?

**Comment by vupham04** [comment]
@saevarom yes, it's on a fresh install, so I have to run manage.py makemigrations by SSH into the environment.

**Comment by vupham04** [comment]
Also, I don't know why, but when I load the new Wagtail on Docker, and then try to access the admin page, it appears like this. I'm not sure if this is a problem with Wagtail in general or Wagtail Docker specifically though.
![image](https://user-images.githubusercontent.com/46913707/160257231-760736bd-fe32-4864-bb00-649bfbdb557c.png)

**Comment by thoang43** [comment]
I confirm that I had the same issue when I ran the freshly installed docker-wagtail-develop. Since the error said it all, I ran the command manage.py makemigrations and manage.py migrate inside the container to fix the problem.

**Comment by cnk** [comment]
I cannot reproduce this with the code available as of October 2023
