### ISSUE TITLE
Web container not launching - windows

### ISSUE THREAD

**Issue by RobertNewton-Nomura** [wagtail/docker-wagtail-develop#46]
Hi, 

I'm trying to get this going on a windows machine, and running in the below error.

```
(venv) PS C:\Users\rob_s\PycharmProjects\Autobiography\wagtail> docker-compose up
time="2022-10-14T09:45:31+01:00" level=warning msg="The \"PYTHONPATH\" variable is not set. Defaulting to a blank string."
[+] Running 3/0
 - Container frontend  Created                                                                                                                                                                                                     0.0s 
 - Container db        Created                                                                                                                                                                                                     0.0s 
 - Container web       Created                                                                                                                                                                                                     0.0s 
Attaching to db, frontend, web
frontend  | Copying node_modules, this may take a few minutes...
db        |
db        | PostgreSQL Database directory appears to contain a database; Skipping initialization
db        |
db        | 2022-10-14 08:45:33.580 UTC [1] LOG:  starting PostgreSQL 12.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit
db        | 2022-10-14 08:45:33.581 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db        | 2022-10-14 08:45:33.581 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db        | 2022-10-14 08:45:33.593 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db        | 2022-10-14 08:45:33.617 UTC [21] LOG:  database system was shut down at 2022-10-14 08:45:27 UTC
db        | 2022-10-14 08:45:33.624 UTC [1] LOG:  database system is ready to accept connections
              0   0%    0.00kB/s    0:00:00 (xfr#0, to-chk=0/71361)   
frontend  | 
frontend  | > wagtail@1.0.0 start
frontend  | > webpack --config ./client/webpack.config.js --mode development --progress --watch
frontend  |
web       | /usr/bin/env: ‘python\r’: No such file or directory
web exited with code 127

```
The database and frontend containers both function as expected, but the web one exits.

I've seen a few [stackoverflows](https://stackoverflow.com/questions/19425857/env-python-r-no-such-file-or-directory) recommending I 
'open the file in vim or vi, and administer the following command:
:set ff=unix
Save and exit:
:wq'
however I'm not sure which file it is I'd need to open in vim and do this with.

Any advice would be much appreciated; thanks in advance!

Have a good one,
Rob

**Comment by zerolab** [comment]
@RobSisson try to do this on https://github.com/wagtail/docker-wagtail-develop/blob/main/docker-compose.yml

**Comment by RobertNewton-Nomura** [comment]
> @RobSisson try to do this on https://github.com/wagtail/docker-wagtail-develop/blob/main/docker-compose.yml

Tried it with still no luck, though I may have done it incorrectly - first time using vim!

Any other ideas?

**Comment by saevarom** [comment]
@RobSisson Could you try editing the  `docker-compose.yml` and change `./manage.py` in line 12 to `python manage.py` ?

**Comment by RobertNewton-Nomura** [comment]
> @RobSisson Could you try editing the  `docker-compose.yml` and change `./manage.py` in line 12 to `python manage.py` ?

Ah sorted! The web container now runs, however no data gets sent when going to localhost:8000 - is this to be expected?

**Comment by RobertNewton-Nomura** [comment]
Tried restarting it and now this comes up:

`Environment:


Request Method: GET
Request URL: http://localhost:8000/

Django Version: 4.0.8
Python Version: 3.8.15
Installed Applications:
['bakerydemo.base',
 'bakerydemo.blog',
 'bakerydemo.breads',
 'bakerydemo.locations',
 'bakerydemo.search',
 'wagtail.contrib.search_promotions',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail.search',
 'wagtail.admin',
 'wagtail.api.v2',
 'wagtail.locales',
 'wagtail.contrib.modeladmin',
 'wagtail.contrib.routable_page',
 'wagtail.contrib.simple_translation',
 'wagtail.contrib.styleguide',
 'wagtail',
 'rest_framework',
 'modelcluster',
 'taggit',
 'wagtailfontawesome',
 'debug_toolbar',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps']
Installed Middleware:
['debug_toolbar.middleware.DebugToolbarMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

The above exception (relation "wagtailcore_site" does not exist
LINE 1: ...reated_at", "wagtailcore_page"."alias_of_id" FROM "wagtailco...
                                                             ^
) was the direct cause of the following exception:
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/wagtail/wagtail/views.py", line 14, in serve
    site = Site.find_for_request(request)
  File "/code/wagtail/wagtail/models/sites.py", line 150, in find_for_request
    site = Site._find_for_request(request)
  File "/code/wagtail/wagtail/models/sites.py", line 160, in _find_for_request
    site = get_site_for_hostname(hostname, port)
  File "/code/wagtail/wagtail/models/sites.py", line 23, in get_site_for_hostname
    sites = list(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)

Exception Type: ProgrammingError at /
Exception Value: relation "wagtailcore_site" does not exist
LINE 1: ...reated_at", "wagtailcore_page"."alias_of_id" FROM "wagtailco...
                                                             ^

`

**Comment by saevarom** [comment]
I think you missed step 7 in the README, you will need to run migrations in the container to populate the database.

**Comment by saevarom** [comment]
> I think you missed step 7 in the README, you will need to run migrations in the container to populate the database.

@RobSisson  That would be this step:

```
# 7. Now in a new shell, run the databse setup script. The database will be persisted across container executions by Docker's Volumes system so you will only need to run this commmand the first time you start the database.
./setup-db.sh
# Success!
```

**Comment by RobertNewton-Nomura** [comment]
All sorted! thanks! 

I found I needed to use 
`docker-compose run web python3 manage.py migrate`
as 
`./setup-db.sh` or running the file in pycharm didnt work

Thanks for your help!

**Comment by saevarom** [comment]
Good to hear! Good luck contributing to Wagtail :)
