### ISSUE TITLE
Setup from stratch will not automatically point to bakerydemo

### ISSUE THREAD

**Issue by peterruijter** [wagtail/docker-wagtail-develop#53]
Hi,

Thanks for creating this repro. I don't have much experience with wagtail and tried to activate this repro on macOS Monterey, after running `docker-compose up` only see "Welcome to your new Wagtail site!" on a completely white page instead of a `bakerydemo`-website. 

I had hoped this repro would bring me up to speed promptly, now I have to start figuring out how to get that one into view, the instructions for that are unfortunately missing. 😞  

Greets, Peter

**Comment by saevarom** [comment]
Hi Peter

Did you run the `setup-db.sh` script as described in step 7 in the README?

**Comment by peterruijter** [comment]
Hi Sævar,

Thanks for your response. 

Yes, I followed all the steps in the README, including running the `setup-db.sh`.

**Comment by saevarom** [comment]
OK, perhaps one of the newer versions broke the setup, I will take a look later

**Comment by peterruijter** [comment]
I went through all the steps again and now it does work. Strange, at least I can get started.
