### ISSUE TITLE
`setup.sh` script attempts to copy file in `bakerydemo` which doesn't exist anymore

### ISSUE THREAD

**Issue by floels** [wagtail/docker-wagtail-develop#54]
Hi,

When running the `setup.sh` script locally to set up my local Wagtail development environment, I got the following error in the terminal:

`Creating local settings file
cp: bakerydemo/bakerydemo/settings/local.py.docker-compose-example: No such file or directory`

The error comes from the following line of the script:

https://github.com/wagtail/docker-wagtail-develop/blob/9ee767966ed70e8caf73426590a208382759bf35/setup.sh#L40

and indeed `bakerydemo/settings/local.py.docker-compose-example` doesn't exist anymore in `bakerydemo`. It was removed in [this PR](https://github.com/wagtail/bakerydemo/pull/393) merged three weeks ago.

I guess the correct command in `setup.sh` would be:

`cp bakerydemo/bakerydemo/settings/local.py.example bakerydemo/bakerydemo/settings/local.py`

I can make a PR to change it if you confirm.

**Comment by saevarom** [comment]
Thanks @floels 

I think that just referencing `local.py` is not sufficient, we need the lines from the old docker compose example file so that the project uses the env variable `DATABASE_URL` to connect to the db.

```python
import dj_database_url

# Override settings here
db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)
```

But I think we can just create our own local settings example file to maintain in this repository. If you want to create a PR then go for it.

**Comment by floels** [comment]
Hi @saevarom,

Thanks for the quick reply. Ok so just to make sure I understand, we would:

1. create a `bakerydemo-settings-local.example` file with the following content:

```python
import dj_database_url

# Override settings here
db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)
```

at the root of this `docker-wagtail-develop` repo,

2. replace:

https://github.com/wagtail/docker-wagtail-develop/blob/9ee767966ed70e8caf73426590a208382759bf35/setup.sh#L40

in `setup.sh` with:

`cp bakerydemo-settings-local.example bakerydemo/bakerydemo/settings/local.py`?

**Comment by saevarom** [comment]
Yes, almost, but the full contents of the `bakerydemo-settings-local.example` would probably need to be:

```python
from bakerydemo.settings.dev import *   # noqa
import dj_database_url

# Override settings here
db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)
```

I omitted the first line to only show what the difference between the files was
