### ISSUE TITLE
docker-compose build throws Command 'docker-compose' not found..

### ISSUE THREAD

**Issue by muditchoudhary** [wagtail/docker-wagtail-develop#57]
I was setting up the wagtail locally through the wagtail docker instruction given, I saw that `docker-compose` command has been renamed to `docker compose` **without a hyphen**. 

So when running a command with `docker-compose` the following output comes:

```
Command 'docker-compose' not found, but can be installed with:
sudo snap install docker          # version 20.10.17, or
sudo apt  install docker-compose  # version 1.29.2-1
See 'snap info docker' for additional versions.
```

But I do have docker.
```
docker --version

Docker version 23.0.3, build 3e7cbfd

docker compose version

Docker Compose version v2.17.2
```

My System Specs and current software versions:

`docker --version`: `Docker version 23.0.3, build 3e7cbfd`
`docker compose version`: `Docker Compose version v2.17.2`
**Using Docker desktop**
`lsb_release -a`: 
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
```

## Possible solutions:

- **Changing the docker-compose to docker compose**: when I was following the instructions I changed the docker-compose to docker compose wherever the command comes. Also in the `setup-db.sh` file.

- **Mention a note in the instructions**: So that new folks won't get confused.

**Comment by zerolab** [comment]
Fixed in #78
