### ISSUE TITLE
bakerydemo.json fixture fails to load when running setup-db.sh

### ISSUE THREAD

**Issue by fadedsky** [wagtail/docker-wagtail-develop#67]
Unable to successfully run `./setup-db.sh` for step 7, specifically the `load_initial_data` manage command.

I did eventually fix the errors by going through each error the `load_initial_data` threw, all which relates to changes for Wagtail 6.0.

Changes I made:
1. Replace `wagtailsearch.query` with `wagtailsearchpromotions.query` model
```
django.core.serializers.base.DeserializationError: Problem installing fixture '/code/bakerydemo/bakerydemo/base/fixtures/bakerydemo.json': Invalid model identifier: 'wagtailsearch.query'
```
2. Replace `wagtailsearch.querydailyhits` with `wagtailsearchpromotions.querydailyhits` model
```
django.core.serializers.base.DeserializationError: Problem installing fixture '/code/bakerydemo/bakerydemo/base/fixtures/bakerydemo.json': Invalid model identifier: 'wagtailsearch.querydailyhits'
```
4. Remove `permission_type` from `wagtailcore.grouppagepermission` model
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/options.py", line 673, in get_field
    return self.fields_map[field_name]
KeyError: 'permission_type'
```
5. Remove `submitted_for_moderation` from `wagtailcore.revision` model
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/models/options.py", line 673, in get_field
    return self.fields_map[field_name]
KeyError: 'submitted_for_moderation'
```

After making those changes, I was able to  run `./setup-db.sh` successfully and the website seems to run fine.

I'll submit a PR to bakerydemo in a bit with the updated fixture.

**Comment by laymonage** [comment]
Fixed in wagtail/bakerydemo#459.
